package org.justforfun.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

// Generated Oct 16, 2016 10:50:15 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Table;

/**
 * Contacts generated by hbm2java
 */
@Table(name = "contacts")
@Entity(name="Contacts")
public class Contacts implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	@Column(name="id")
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name="user_id",insertable=false,nullable=false,updatable=false)
	private Integer userId;
	
	@ManyToOne(fetch=FetchType.LAZY,targetEntity=Users.class)
	@JoinColumn(name="user_id")
	private Users users;
	
	@Column(name="telephone")
	private String telephone;
	
	@Column(name="email")
	private String email;

	public Contacts() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
