package org.justforfun.entity;
// default package

// Generated Oct 16, 2016 10:50:15 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Table(name="users")
@Entity(name="Users")
public class Users implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	@Column(name="id")
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="firstName")
	private String firstName;
	@Column(name="lastName")
	private String lastName;
	@Column(name="age")
	private int age;
	
	@OneToMany(targetEntity=Contacts.class,mappedBy="userId")
	private Set<Contacts> contactses = new HashSet<Contacts>(0);
	@OneToMany(targetEntity=Authentications.class,mappedBy="userId")
	private Set<Authentications> authenticationses = new HashSet<Authentications>(0);

	public Users() { 
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Set<Contacts> getContactses() {
		return this.contactses;
	}

	public void setContactses(Set<Contacts> contactses) {
		this.contactses = contactses;
	}

	public Set<Authentications> getAuthenticationses() {
		return this.authenticationses;
	}

	public void setAuthenticationses(Set<Authentications> authenticationses) {
		this.authenticationses = authenticationses;
	}

}
